### ISSUE TITLE
[BUG] """default field""" empty: String

### ISSUE THREAD

**Issue by Eddie-CooRo** [yarax/swagger-to-graphql#86]
Hi
when I use swagger-to-graphql in order to translate swaggers default "Pet store" project to graphql there is a lot of types with just one field that is empty: String. what are these?

**Comment by yarax** [comment]
That came from the fact, that graphql.js didn't pass object types without properties. https://github.com/yarax/swagger-to-graphql/blob/e77699a9fc3a2fac84e941e81abbacc4308d7f74/src/typeMap.js#L107
I guess now it's possible, so we should actually recheck it

**Comment by Eddie-CooRo** [comment]
I didn't know that...
What about this one???

```
createUsersWithArrayInput(body: param_createUsersWithArrayInput_bodyInput!): createUsersWithArrayInput

"""
List of user object
"""
input param_createUsersWithArrayInput_bodyInput {
  """default field"""
  empty: String
}
```

And here is the actual YAML definition:
```
  /user/createWithList:
    post:
      tags:
      - user
      summary: Creates list of users with given input array
      operationId: createUsersWithListInput
      produces:
      - application/json
      - application/xml
      parameters:
      - in: body
        name: body
        description: List of user object
        required: true
        schema:
          type: array
          items:
            $ref: '#/definitions/User'
      responses:
        default:
          description: successful operation
```

Why is that??

**Comment by yarax** [comment]
From your example it's not clear what the User type is

**Comment by Eddie-CooRo** [comment]
Oh...
here is the User:
```
User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      username:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      password:
        type: string
      phone:
        type: string
      userStatus:
        type: integer
        format: int32
        description: User Status
    xml:
      name: User
```

So I wonder why the _param_createUsersWithArrayInput_bodyInput_ is empty?
